version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./app:/app
      - ./vendor:/vendor
      - ./images:/images
    depends_on:
      - mysql_db


  mysql_db:
    build:
      context: .
      dockerfile: mysql.Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./mysql:/var/lib/mysql